apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  # the persistent volume claim tells kubernetes to try to find a storage option that meets this requirements
  accessModes:
    # can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
